services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./backend/infra/app/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    container_name: nginx
    image: nginx
    working_dir: /app
    tty: true
    ports:
      - ${WEB_PORT}:80
    volumes:
      - .:/app
      - ./backend/infra/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./backend/infra/db/data:/var/lib/mysql
      - ./backend/infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 40080:80
    volumes:
      - ./backend/infra/phpmyadmin/sessions:/sessions

  frontend:
    container_name: frontend
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    tty: true
